//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fridge
    {
        public int FridgeID { get; set; }
        public int Mass { get; set; }
        public decimal Volume { get; set; }
        public System.DateTime ManufacturedOn { get; set; }
        public string Customer { get; set; }
        public string DeliveringDriverPersonalCode { get; set; }
        public Nullable<System.DateTime> DeliverUntil { get; set; }
        public Nullable<System.DateTime> DeliveredAt { get; set; }
    
        public virtual Customer Customer1 { get; set; }
        public virtual Driver Driver { get; set; }
    }
}
